[workspace]
members=[
    'wasm-bindgen-derive-macro',
    'wasm-bindgen-derive',
    'tests'
]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
license = "MIT"
repository = "https://github.com/fjarri/wasm-bindgen-derive"
rust-version = "1.96.0"

[workspace.dependencies]
js-sys = "0.3.103"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
wasm-bindgen = "=0.2.126"
wasm-bindgen-derive-macro = { path = "./wasm-bindgen-derive-macro" }
wasm-bindgen-test = "0.3.76"
