[workspace]
members=[
    'wasm-bindgen-derive-macro',
    'wasm-bindgen-derive',
    'tests'
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
license = "MIT"
repository = "https://github.com/fjarri/wasm-bindgen-derive"
rust-version = "1.85.0"

[workspace.dependencies]
js-sys = "0.3.97"
wasm-bindgen = "0.2.120"
