[package]
name = "wasm-bindgen-derive-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wasm-bindgen-derive = { path = "../wasm-bindgen-derive" }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
