[package]
name = "wasm-bindgen-derive-macro"
version = "0.3.0"
edition = "2024"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
license = "MIT"
description = "Proc-macro backend for wasm-bindgen-derive"
repository = "https://github.com/fjarri/wasm-bindgen-derive"
categories = ["no-std", "wasm"]
rust-version = "1.85.0"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
wasm-bindgen = "=0.2.89"
js-sys = "0.3.55"
