[package]
name = "wasm-bindgen-derive"
version = "0.4.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Trait derivation macros for wasm-bindgen"
readme = "../README.md"
categories = ["no-std", "wasm"]

[dependencies]
wasm-bindgen-derive-macro = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
